### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by sethaxen** [matt-graham/mici#2]
It would be nice to have a test suite in the repo, perhaps set up with Travis CI for continuous integration. This would both demonstrate how to use the package and also show that it works.

**Comment by matt-graham** [comment]
I agree that it would be a very good idea to have a test suite! I previously had a few tests set up in a previous version, but removed these when reorganising the package with the intention of adding a more complete set of tests at a later point, but have never quite got around to this... At the moment I'm in the midst of another project and won't have time to work on this immediately however I will try my best to prioritise working on this once I have more time again.

**Comment by matt-graham** [comment]
Test suite now has reasonable coverage of the package and continuous integration set up with Github Actions, so (finally) closing this issue.
